name: main
on:
  push:
    branches:
      - trunk

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
